# Gate definitions
SINGLE_QUBIT_GATES = {"H", "X", "Y", "Z", "S", "T"}
ROTATION_GATES = {"RX", "RY", "RZ"}
TWO_QUBIT_GATES = {"CNOT", "CX", "SWAP", "CZ"}

ALL_SUPPORTED_GATES = SINGLE_QUBIT_GATES | ROTATION_GATES | TWO_QUBIT_GATES

MAX_QUBITS = 12
MIN_QUBITS = 1
MAX_SHOTS = 8192
MIN_SHOTS = 1
